[package]
name = "transaction-processor"
version = "1.0.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
env_logger = "0.11.3"
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }

[dev-dependencies]
tempfile = "3.12.0"
